#!/bin/sh
#
# @name AEROARMS SITL
#
# @type Hexarotor x
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.2
	param set MC_PITCHRATE_I 0.05
	param set MC_PITCH_P 6.0
	param set MC_ROLLRATE_P 0.2
	param set MC_ROLLRATE_I 0.1
	param set MC_ROLL_P 6.0
	param set MPC_XY_VEL_MAX 2.0
	param set MPC_VEL_MANUAL 2.0
	param set MPC_XY_CRUISE 2.0

	param set RTL_DESCEND_ALT 10
	param set RTL_LAND_DELAY 0
fi

set MAV_TYPE 13

set MIXER hexa_x
